services:
  monitor-api:
    build: .
    container_name: monitor-api
    restart: unless-stopped
    ports:
      - "7777:7000"

    env_file:
      - .env
    
    volumes:
      - ./src/app/logs:/app/logs
      - /:/host:ro,rslave
      - /proc:/host/proc:ro

  mongodb:
    image: mongo:7
    container_name: monitor-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  itouposts-network:
    driver: bridge