#----------------------------------------------------------
# My Terraform
# Provision:
#  - S3 Backend for remote Terraform state
#  - AWS Provider configuration
#  - TLS Provider for SSH key generation
#  - Local Provider for saving private key locally
#  - Network remote state lookup
#  - Security remote state lookup
#  - SSH Key Pair generated by Terraform
#  - Public Web EC2 instance
#  - Private MongoDB EC2 instance
#  Dmytro Shpatakovskyi
#-------------------Backend----------------------

provider "aws" {
  region = "us-east-1"
}

terraform {
  backend "s3" {
    bucket = "dev-terraform-state-int26-39"
    key    = "dev/instances/terraform.tfstate"
    region = "us-east-1"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

#-------------------------Remote State---------------------------------
data "terraform_remote_state" "network" {
  backend = "s3"

  config = {
    bucket = "dev-terraform-state-int26-39"
    key    = "dev/network/terraform.tfstate"
    region = "us-east-1"
  }
}

data "terraform_remote_state" "security" {
  backend = "s3"

  config = {
    bucket = "dev-terraform-state-int26-39"
    key    = "dev/security/terraform.tfstate"
    region = "us-east-1"
  }
}


#-------------------------Key Pair Generate by Terraform-------------------------

resource "tls_private_key" "login" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "login" {
  key_name   = "${var.env}-terraform-key"
  public_key = tls_private_key.login.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.login.private_key_pem
  filename        = "${path.module}/keys/id_rsa"
  file_permission = "0600"
}

#-------------------------EC2 Instances-------------------------

resource "aws_instance" "web" {
  ami                         = "ami-05cf1e9f73fbad2e2" # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
  instance_type               = "t3.micro"
  subnet_id                   = data.terraform_remote_state.network.outputs.public_subnet_id_a
  vpc_security_group_ids      = [data.terraform_remote_state.security.outputs.security_gr_web]
  associate_public_ip_address = true
  key_name                    = aws_key_pair.login.key_name

  tags = {
    Name = "${var.env}-web-instance"
  }
}

resource "aws_instance" "mongodb" {
  ami                    = "ami-05cf1e9f73fbad2e2" # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
  instance_type          = "t3.micro"
  subnet_id              = data.terraform_remote_state.network.outputs.private_subnet_id_a
  vpc_security_group_ids = [data.terraform_remote_state.security.outputs.security_gr_mongodb]
  key_name               = aws_key_pair.login.key_name

  tags = {
    Name = "${var.env}-mongodb-instance"
  }
}