apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: registry-auth
              mountPath: /auth
              readOnly: true
      volumes:
        - name: registry-storage
          hostPath:
            path: /opt/registry/data
            type: DirectoryOrCreate
        - name: registry-auth
          secret:
            secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: private-registry
  namespace: registry
spec:
  type: NodePort
  selector:
    app: private-registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 30500
