apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: cars-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "cars_admin"
  MONGO_INITDB_ROOT_PASSWORD: "cars_admin_password"