apiVersion: v1
kind: Secret
metadata:
  name: monitor-api-secret
  namespace: cars-app
type: Opaque
stringData:
  MONGO_URI: "mongodb://cars_admin:cars_admin_password@mongodb:27017/cars_db?authSource=admin"